---
hostname: kng01-mgmt-zabbix-01
site: kng01
zone: mgmt
role: zabbix
virtualization_type: vm
os_distribution: Ubuntu
os_version: "26.04"

network_address: 10.10.10.250/24
network_ipv4_address: 10.10.10.250
network_prefix_length: 24
network_gateway: 10.10.10.1
network_dns_resolvers:
  - 10.10.10.240
  - 10.10.10.241
network_primary_fqdn: kng01-mgmt-zabbix-01.srv.alflag.internal
network_service_aliases:
  - zabbix.alflag.internal

systemd_resolved_dns:
  - 10.10.10.240
  - 10.10.10.241
systemd_resolved_domains:
  - srv.alflag.internal

ssh_server_enabled: true
systemd_resolved_enabled: true
foundation_vm_skip_systemd_resolved: true
foundation_vm_skip_zabbix_agent: true
zabbix_agent_enabled: true
