---
- name: Ensure LXC operator account  # noqa role-name[path]
  ansible.builtin.include_role:
    name: foundation/operator
    public: true

- name: Configure LXC locale
  ansible.builtin.include_tasks:
    file: locale.yml
  when: not foundation_lxc_skip_locale | bool

- name: Install LXC base packages
  ansible.builtin.include_tasks:
    file: packages.yml

- name: Configure LXC unattended upgrades
  ansible.builtin.include_tasks:
    file: unattended_upgrades.yml
  when: not foundation_lxc_skip_unattended_upgrades | bool

- name: Prepare LXC operator home
  ansible.builtin.include_tasks:
    file: home.yml
  when: not foundation_lxc_skip_home | bool

- name: Sync LXC operator secrets
  ansible.builtin.include_tasks:
    file: secrets.yml
  when: not foundation_lxc_skip_secrets | bool
