---
- name: Install LXC base packages
  ansible.builtin.include_role:
    name: apt_state
  vars:
    apt_state_packages: "{{ foundation_lxc_packages }}"
    apt_state_become: "{{ foundation_lxc_become_root }}"
