---
- name: Install unattended-upgrades
  ansible.builtin.apt:
    name:
      - unattended-upgrades
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time | default(86400) }}"
  become: "{{ foundation_lxc_become_root }}"

- name: Copy 20auto-upgrades
  ansible.builtin.copy:
    src: ./etc/apt/apt.conf.d/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"
  become: "{{ foundation_lxc_become_root }}"
  notify: Restart LXC unattended-upgrades

- name: Copy 50unattended-upgrades
  ansible.builtin.copy:
    src: ./etc/apt/apt.conf.d/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: "0644"
  become: "{{ foundation_lxc_become_root }}"
  notify: Restart LXC unattended-upgrades
