---
- name: Enable ja_JP.UTF-8 locale
  ansible.builtin.lineinfile:
    path: /etc/locale.gen
    regexp: '^#?\s*ja_JP\.UTF-8\s+UTF-8$'
    line: ja_JP.UTF-8 UTF-8
    create: false
    owner: root
    group: root
    mode: "0644"
  notify: Generate VM ja_JP.UTF-8 locale
  become: true
