---
- name: Set VM hostname
  ansible.builtin.include_tasks:
    file: hostname.yml

- name: Configure VM timezone
  ansible.builtin.include_tasks:
    file: timezone.yml

- name: Configure VM locale
  ansible.builtin.include_tasks:
    file: locale.yml

- name: Install VM base packages
  ansible.builtin.include_tasks:
    file: packages.yml

- name: Ensure VM operator account  # noqa role-name[path]
  ansible.builtin.include_role:
    name: foundation/operator

- name: Configure VM swap policy
  ansible.builtin.include_tasks:
    file: swap.yml
  when:
    - not foundation_vm_skip_swap | bool
    - ansible_facts.get('virtualization_type', '') != 'lxc'

- name: Configure VM unattended upgrades
  ansible.builtin.include_tasks:
    file: unattended_upgrades.yml
  when:
    - not foundation_vm_skip_unattended_upgrades | bool
    - ansible_facts.get('virtualization_type', '') != 'lxc'
