---
- name: Install unattended-upgrades
  ansible.builtin.include_role:
    name: apt_state
  vars:
    daedalus_apt_packages:
      - unattended-upgrades

- name: Copy 20auto-upgrades
  ansible.builtin.copy:
    src: ./etc/apt/apt.conf.d/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Restart VM unattended-upgrades

- name: Copy 50unattended-upgrades
  ansible.builtin.copy:
    src: ./etc/apt/apt.conf.d/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Restart VM unattended-upgrades
