---
- name: Converge shared foundation
  hosts: default
  gather_facts: true

  roles:
    - role: foundation/platform_vm  # noqa role-name[path]
      when: "'platform_vm' in group_names"
    - role: foundation/platform_lxc  # noqa role-name[path]
      when: "'platform_lxc' in group_names"
    - role: atlas_host
    - role: ssh_server
      when: ssh_server_enabled | default(false)
    - role: systemd_resolved
      when: systemd_resolved_enabled | default(false)
    - role: node_exporter
      when: node_exporter_enabled | default(false)
