---
- name: Converge DNS services
  ansible.builtin.import_playbook: services/dns.yml

- name: Converge web origin services
  ansible.builtin.import_playbook: services/web.yml

- name: Converge shared MySQL data services
  ansible.builtin.import_playbook: services/mysql.yml

- name: Converge monitoring services
  ansible.builtin.import_playbook: services/monitoring.yml

- name: Converge NetBox service
  ansible.builtin.import_playbook: services/netbox.yml
