---
- name: restart zabbix-server
  ansible.builtin.service:
    name: "{{ zabbix_server_service_name }}"
    state: restarted
    enabled: true
  when: not ansible_check_mode

- name: restart zabbix php-fpm
  ansible.builtin.service:
    name: "{{ zabbix_server_php_fpm_service_name }}"
    state: restarted
    enabled: true
  when: not ansible_check_mode

- name: reload caddy
  ansible.builtin.service:
    name: "{{ zabbix_server_caddy_service_name }}"
    state: reloaded
    enabled: true
  when: not ansible_check_mode

- name: restart mysql
  ansible.builtin.service:
    name: mysql
    state: restarted
    enabled: true
  when: not ansible_check_mode
