---
- name: Restart Zabbix server
  ansible.builtin.service:
    name: "{{ zabbix_server_service_name }}"
    state: restarted
    enabled: true
  when: not ansible_check_mode

- name: Restart Zabbix PHP-FPM
  ansible.builtin.service:
    name: "{{ zabbix_server_php_fpm_service_name }}"
    state: restarted
    enabled: true
  when: not ansible_check_mode

- name: Reload Caddy
  ansible.builtin.service:
    name: "{{ zabbix_server_caddy_service_name }}"
    state: reloaded
    enabled: true
  when: not ansible_check_mode

- name: Restart MySQL
  ansible.builtin.service:
    name: mysql
    state: restarted
    enabled: true
  when: not ansible_check_mode
