---
all:
  children:
    topmost01:
      children:
        topmost01_mgmt:
          hosts:
            topmost01-mgmt-dns-recursive-01:
              ansible_host: 10.10.10.240
            topmost01-mgmt-dns-recursive-02:
              ansible_host: 10.10.10.241
            topmost01-mgmt-dns-authoritative-01:
              ansible_host: 10.10.10.242
            topmost01-mgmt-dns-authoritative-02:
              ansible_host: 10.10.10.243
            topmost01-mgmt-zabbix-01:
              ansible_host: 10.10.10.250
            topmost01-mgmt-mysql-shared-01:
              ansible_host: 10.10.10.221
            topmost01-mgmt-connector-01:
              ansible_host: 10.10.10.41
            topmost01-mgmt-connector-02:
              ansible_host: 10.10.10.42
            topmost01-mgmt-bastion-01:
              ansible_host: 10.10.10.60
            topmost01-mgmt-workbench-01:
              ansible_host: 10.10.10.61
            topmost01-mgmt-control-01:
              ansible_host: 10.10.10.62

        topmost01_dmz:
          hosts:
            topmost01-dmz-web-01:
              ansible_host: 10.10.30.21

        provider_proxmox:
          hosts:
            topmost01-mgmt-dns-recursive-01: {}
            topmost01-mgmt-dns-recursive-02: {}
            topmost01-mgmt-dns-authoritative-01: {}
            topmost01-mgmt-dns-authoritative-02: {}
            topmost01-mgmt-zabbix-01: {}
            topmost01-mgmt-mysql-shared-01: {}
            topmost01-mgmt-connector-01: {}
            topmost01-mgmt-connector-02: {}
            topmost01-mgmt-bastion-01: {}
            topmost01-mgmt-workbench-01: {}
            topmost01-mgmt-control-01: {}
            topmost01-dmz-web-01: {}

        platform_lxc:
          hosts:
            topmost01-mgmt-dns-recursive-01: {}
            topmost01-mgmt-dns-recursive-02: {}
            topmost01-mgmt-dns-authoritative-01: {}
            topmost01-mgmt-dns-authoritative-02: {}
            topmost01-mgmt-connector-01: {}
            topmost01-mgmt-connector-02: {}
            topmost01-mgmt-bastion-01: {}

        platform_vm:
          hosts:
            topmost01-mgmt-control-01: {}
            topmost01-mgmt-zabbix-01: {}
            topmost01-mgmt-mysql-shared-01: {}
            topmost01-mgmt-workbench-01: {}
            topmost01-dmz-web-01: {}

        cap_atlas_host:
          hosts:
            topmost01-mgmt-control-01: {}

        cap_control_node:
          hosts:
            topmost01-mgmt-control-01: {}

        svc_dns_recursive:
          hosts:
            topmost01-mgmt-dns-recursive-01: {}
            topmost01-mgmt-dns-recursive-02: {}

        svc_dns_authoritative:
          hosts:
            topmost01-mgmt-dns-authoritative-01: {}
            topmost01-mgmt-dns-authoritative-02: {}

        svc_connector:
          hosts:
            topmost01-mgmt-connector-01: {}
            topmost01-mgmt-connector-02: {}

        svc_bastion:
          hosts:
            topmost01-mgmt-bastion-01: {}

        svc_workbench:
          hosts:
            topmost01-mgmt-workbench-01: {}

        svc_zabbix:
          hosts:
            topmost01-mgmt-zabbix-01: {}

        svc_mysql:
          hosts:
            topmost01-mgmt-mysql-shared-01: {}

        svc_web:
          hosts:
            topmost01-dmz-web-01: {}
