---
- name: Reload PostgreSQL
  ansible.builtin.systemd_service:
    name: "{{ services_netbox_postgresql_service_name }}"
    state: reloaded
  when: not ansible_check_mode

- name: Restart Redis
  ansible.builtin.systemd_service:
    name: "{{ services_netbox_redis_service_name }}"
    state: restarted
    enabled: true
  when: not ansible_check_mode

- name: Restart NetBox services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: restarted
    enabled: true
    daemon_reload: true
  loop:
    - "{{ services_netbox_service_name }}"
    - "{{ services_netbox_worker_service_name }}"
  when: not ansible_check_mode
