---
all:
  children:
    kanagawa01:
      children:
        kng01_mgmt:
          hosts:
            kng01-mgmt-recdns-01:
              ansible_host: 10.10.10.240
            kng01-mgmt-recdns-02:
              ansible_host: 10.10.10.241
            kng01-mgmt-authdns-01:
              ansible_host: 10.10.10.242
            kng01-mgmt-authdns-02:
              ansible_host: 10.10.10.243
            kng01-mgmt-zabbix-01:
              ansible_host: 10.10.10.250
            kng01-mgmt-mysql-01:
              ansible_host: 10.10.10.251
            kng01-mgmt-connector-01:
              ansible_host: 10.10.10.41
            kng01-mgmt-connector-02:
              ansible_host: 10.10.10.42
            kng01-mgmt-bastion-01:
              ansible_host: 10.10.10.60
            kng01-mgmt-workbench-01:
              ansible_host: 10.10.10.61
            kng01-mgmt-control-01:
              ansible_host: 10.10.10.62

        kng01_dmz:
          hosts:
            kng01-dmz-web-01:
              ansible_host: 10.10.30.21

        provider_proxmox:
          hosts:
            kng01-mgmt-recdns-01: {}
            kng01-mgmt-recdns-02: {}
            kng01-mgmt-authdns-01: {}
            kng01-mgmt-authdns-02: {}
            kng01-mgmt-zabbix-01: {}
            kng01-mgmt-mysql-01: {}
            kng01-mgmt-connector-01: {}
            kng01-mgmt-connector-02: {}
            kng01-mgmt-bastion-01: {}
            kng01-mgmt-workbench-01: {}
            kng01-mgmt-control-01: {}
            kng01-dmz-web-01: {}

        platform_lxc:
          hosts:
            kng01-mgmt-recdns-01: {}
            kng01-mgmt-recdns-02: {}
            kng01-mgmt-authdns-01: {}
            kng01-mgmt-authdns-02: {}
            kng01-mgmt-connector-01: {}
            kng01-mgmt-connector-02: {}
            kng01-mgmt-bastion-01: {}
            kng01-mgmt-workbench-01: {}

        platform_vm:
          hosts:
            kng01-mgmt-control-01: {}
            kng01-mgmt-zabbix-01: {}
            kng01-mgmt-mysql-01: {}
            kng01-dmz-web-01: {}

        cap_atlas_host:
          hosts:
            kng01-mgmt-control-01: {}

        cap_control_node:
          hosts:
            kng01-mgmt-control-01: {}

        svc_dns_recursive:
          hosts:
            kng01-mgmt-recdns-01: {}
            kng01-mgmt-recdns-02: {}

        svc_dns_authoritative:
          hosts:
            kng01-mgmt-authdns-01: {}
            kng01-mgmt-authdns-02: {}

        svc_connector:
          hosts:
            kng01-mgmt-connector-01: {}
            kng01-mgmt-connector-02: {}

        svc_bastion:
          hosts:
            kng01-mgmt-bastion-01: {}

        svc_workbench:
          hosts:
            kng01-mgmt-workbench-01: {}

        svc_zabbix:
          hosts:
            kng01-mgmt-zabbix-01: {}

        svc_mysql:
          hosts:
            kng01-mgmt-mysql-01: {}

        svc_web:
          hosts:
            kng01-dmz-web-01: {}
