---
- name: Install Caddy repository prerequisites
  ansible.builtin.include_role:
    name: apt_state
  vars:
    daedalus_apt_packages:
      - ca-certificates
      - python3-debian

- name: Add Caddy repository
  ansible.builtin.deb822_repository:
    name: caddy-stable
    types:
      - deb
    uris:
      - https://dl.cloudsmith.io/public/caddy/stable/deb/debian
    suites:
      - any-version
    components:
      - main
    signed_by: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    state: present
  register: caddy_repository

- name: Install Caddy
  ansible.builtin.include_role:
    name: apt_state
  vars:
    daedalus_apt_packages: caddy
    daedalus_apt_force_update_cache: "{{ caddy_repository.changed | default(false) }}"
