---
- name: Copy mysqld.cnf
  ansible.builtin.copy:
    src: ./etc/mysql/mysql.conf.d/mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: "0644"
  notify: Restart MySQL

- name: Create Zabbix Database
  ansible.mysql.mysql_db:
    login_user: "root"
    login_unix_socket: "{{ mysql_login_unix_socket }}"
    name: "{{ mysql_zabbix_dbname }}"
    encoding: utf8mb4
    collation: utf8mb4_bin
    state: present

- name: Create Zabbix User
  ansible.mysql.mysql_user:
    login_user: "root"
    login_unix_socket: "{{ mysql_login_unix_socket }}"
    name: "{{ mysql_zabbix_user }}"
    host: "localhost"
    plugin: "{{ mysql_zabbix_auth_plugin }}"
    plugin_auth_string: "{{ mysql_zabbix_password }}"
    salt: "{{ mysql_zabbix_password_salt }}"
    priv: "{{ mysql_zabbix_dbname }}.*:ALL"
    state: present
  no_log: true

- name: Create zabbix_monitor User
  ansible.mysql.mysql_user:
    login_user: "root"
    login_unix_socket: "{{ mysql_login_unix_socket }}"
    name: "{{ mysql_zabbix_monitor_user }}"
    host: "127.0.0.1"
    plugin: "{{ mysql_zabbix_auth_plugin }}"
    plugin_auth_string: "{{ mysql_zabbix_monitor_password }}"
    salt: "{{ mysql_zabbix_monitor_password_salt }}"
    priv: "*.*:REPLICATION CLIENT,PROCESS,SHOW DATABASES,SHOW VIEW"
    state: present
  no_log: true

- name: Manage Zabbix database schema
  ansible.builtin.include_tasks:
    file: mysql_schema.yml
