---
- name: Ensure Zabbix PHP-FPM config directory exists
  ansible.builtin.file:
    path: "{{ zabbix_server_php_fpm_ini_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy 99-zabbix.ini
  ansible.builtin.template:
    src: ./etc/php/fpm/conf.d/99-zabbix.ini
    dest: "{{ zabbix_server_php_fpm_zabbix_ini_path }}"
    owner: root
    group: root
    mode: "0644"
  notify: restart zabbix php-fpm

- name: Enable and start Zabbix PHP-FPM
  ansible.builtin.systemd_service:
    name: "{{ zabbix_server_php_fpm_service_name }}"
    enabled: true
    state: started
  when: not ansible_check_mode
