---
- name: Install Zabbix Server
  ansible.builtin.apt:
    name: "{{ zabbix_server_packages }}"
    state: present
    update_cache: true

- name: Copy Zabbix Server Configuration
  ansible.builtin.template:
    src: ./etc/zabbix/zabbix_server.conf
    dest: /etc/zabbix/zabbix_server.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart zabbix-server

- name: Create Symbolic Link
  ansible.builtin.file:
    src: /usr/share/fonts/opentype/ipafont-gothic/ipag.ttf
    dest: /usr/share/zabbix/assets/fonts/ipag.ttf
    state: link
  notify: restart zabbix-server

- name: Replace ZBX_GRAPH_FONT_NAME
  ansible.builtin.lineinfile:
    path: /usr/share/zabbix/include/defines.inc.php
    regexp: "^define\\('ZBX_GRAPH_FONT_NAME',.*$"
    line: "define('ZBX_GRAPH_FONT_NAME', 'ipag');"
  notify: restart zabbix-server
