---
- name: Install mysql-server
  ansible.builtin.apt:
    name:
      - mysql-server
      - mysql-client
      - python3-pymysql  # Required for Ansible
      - python3-cryptography  # Required for caching_sha2_password via PyMySQL
      - python3-setuptools  # Required for Ansible
    state: present

- name: Start mysql
  ansible.builtin.systemd_service:
    name: mysql
    state: started
    enabled: true

- name: Remove anonymous users
  ansible.mysql.mysql_user:
    login_user: "root"
    login_unix_socket: "{{ mysql_login_unix_socket }}"
    name: ""
    host_all: true
    state: absent
