---
- name: Converge recursive DNS hosts
  hosts: svc_dns_recursive
  gather_facts: true

  roles:
    - role: services/dns_recursive  # noqa role-name[path]

- name: Converge authoritative DNS hosts
  hosts: svc_dns_authoritative
  gather_facts: true

  roles:
    - role: services/dns_authoritative  # noqa role-name[path]
