---
- name: Converge DNS hosts
  hosts: topmost01
  gather_facts: true

  roles:
    - role: dns_recursor
      when: dns_recursor_enabled | default(false)
    - role: dns_authoritative
      when: dns_authoritative_enabled | default(false)
