---
- name: Converge monitoring service hosts
  hosts: svc_monitoring
  gather_facts: true

  roles:
    - role: services/monitoring  # noqa role-name[path]
      when: monitoring_stack_enabled | default(false)
