---
- name: Converge shared MySQL data service hosts
  hosts: svc_mysql
  gather_facts: true

  roles:
    - role: zabbix_agent
      when: zabbix_agent_enabled | default(false)
    - role: middleware/mysql-server  # noqa role-name[path]
      when: mysql_server_enabled | default(false)
