---
dns_authoritative_enabled: true
dns_authoritative_soa:
  mname: dns-authoritative01.srv.alflag.internal.
  rname: hostmaster.alflag.internal.
  refresh: 3600
  retry: 900
  expire: 604800
  minimum: 300
dns_authoritative_nameservers:
  - dns-authoritative01.srv.alflag.internal.
  - dns-authoritative02.srv.alflag.internal.
dns_authoritative_zones:
  - name: alflag.internal
    managed: true

  - name: srv.alflag.internal
    managed: true
    inventory_records: server_identity
    runtime_record_files:
      - /etc/nsd/runtime/mysql-role-records.zone

  - name: access.internal
    managed: true
    inventory_records: access_aliases

  - name: 10.10.10.in-addr.arpa
    managed: true
    inventory_records: reverse_ptr

  - name: 10.10.30.in-addr.arpa
    managed: true
    inventory_records: reverse_ptr
