---
- name: Remove managed etckeeper push hook
  ansible.builtin.file:
    path: /etc/etckeeper/commit.d/99push
    state: absent

- name: Remove etckeeper package
  ansible.builtin.apt:
    name: etckeeper
    state: absent
    purge: true

- name: Remove managed etckeeper configuration
  ansible.builtin.file:
    path: /etc/etckeeper/etckeeper.conf
    state: absent
