---
- name: Sync secrets
  ansible.builtin.synchronize:
    src: "~/secrets/"
    dest: "{{ common_operator_home }}/secrets"
    mode: push
    recursive: yes

- name: Ensure synced secrets are owned by the LXC operator
  ansible.builtin.file:
    path: "{{ common_operator_home }}/secrets"
    state: directory
    owner: "{{ common_operator_user }}"
    group: "{{ common_operator_group }}"
    recurse: true
  become: true
