---
- name: Copy operator .ssh/config
  ansible.builtin.copy:
    src: ./root/.ssh/config
    dest: "{{ common_lxc_operator_home }}/.ssh/config"
    owner: "{{ common_lxc_operator_user }}"
    group: "{{ common_lxc_operator_group }}"
    mode: 0644
  become: true
