---
ansible_connection: local
ansible_become: true
ansible_python_interpreter: /usr/bin/python3

network_primary_fqdn: mgmt-control-01.srv.alflag.internal

atlas_role: control

ssh_server_enabled: true
