---
role: dns_recursive
virtualization_type: lxc
os_distribution: Ubuntu
os_version: "26.04"

dns_recursor_enabled: true
dns_recursor_listen_addresses:
  - "127.0.0.1"
  - "{{ network_ipv4_address }}"
