---
role: dns_authoritative
virtualization_type: lxc
os_distribution: Ubuntu
os_version: "26.04"

dns_authoritative_enabled: true
dns_authoritative_listen_addresses:
  - "127.0.0.1"
  - "{{ network_ipv4_address }}"
