---
hostname: monitor01
zone: mgmt
role: monitor
virtualization_type: vm
os_distribution: Ubuntu
os_version: "26.04"

network_address: 10.10.10.250/24
network_ipv4_address: 10.10.10.250
network_prefix_length: 24
network_gateway: 10.10.10.1
network_dns_resolvers:
  - 10.10.10.240
  - 10.10.10.241
network_primary_fqdn: monitor01.srv.alflag.internal
network_service_aliases:
  - monitor.srv.alflag.internal
  - prometheus.srv.alflag.internal
  - grafana.srv.alflag.internal
  - alertmanager.srv.alflag.internal

systemd_resolved_dns:
  - 10.10.10.240
  - 10.10.10.241
systemd_resolved_domains:
  - srv.alflag.internal

ssh_server_enabled: true
systemd_resolved_enabled: true

node_exporter_enabled: true

monitoring_stack_enabled: true
prometheus_enabled: true
alertmanager_enabled: true
grafana_enabled: true
blackbox_exporter_enabled: true
