---
ansible_user: ops
ansible_become: true

hostname: web01
zone: dmz
role: web
virtualization_type: vm
os_distribution: Ubuntu
os_version: "26.04"

network_address: 10.10.30.21/24
network_ipv4_address: 10.10.30.21
network_prefix_length: 24
network_gateway: 10.10.30.1
network_dns_resolvers:
  - 10.10.10.240
  - 10.10.10.241
network_primary_fqdn: dmz-web-01.srv.alflag.internal
network_service_aliases:
  - web.access.internal

ssh_server_enabled: true
cloudflare_ssh_enabled: true
cloudflare_ssh_hostname: web01
cloudflared_enabled: true

services_web_origin_enabled: true
services_web_origin_listen_address: 127.0.0.1
services_web_origin_port: 8080
services_web_origin_server_name: web01
