---
role: workbench
virtualization_type: vm
os_distribution: Ubuntu
os_version: "26.04"

network_service_aliases:
  - workbench.access.internal

ssh_server_enabled: true
ssh_server_allow_tcp_forwarding: local
cloudflare_ssh_enabled: true
systemd_resolved_enabled: true
