---
prometheus_enabled: false
prometheus_package: prometheus
prometheus_service_name: prometheus
prometheus_config_dir: /etc/prometheus
prometheus_config_path: /etc/prometheus/prometheus.yml
prometheus_rules_dir: /etc/prometheus/rules
prometheus_file_sd_dir: /var/lib/prometheus/file_sd
prometheus_promtool_binary: /usr/bin/promtool
prometheus_scrape_interval: 30s
prometheus_evaluation_interval: 30s
prometheus_listen_address: 127.0.0.1
prometheus_port: 9090
alertmanager_url: http://127.0.0.1:9093

prometheus_node_exporter_target_group: default
prometheus_node_exporter_file_sd_path: "{{ prometheus_file_sd_dir }}/node.json"
prometheus_node_exporter_target_minimum: 1

prometheus_blackbox_http_file_sd_path: "{{ prometheus_file_sd_dir }}/blackbox_http.json"
prometheus_blackbox_http_targets: []
prometheus_blackbox_http_target_minimum: 0
