---
- name: Restart LXC unattended-upgrades
  ansible.builtin.systemd_service:
    name: unattended-upgrades
    state: restarted
    enabled: true
  become: "{{ foundation_lxc_become_root }}"

- name: Generate LXC ja_JP.UTF-8 locale
  ansible.builtin.command:
    cmd: locale-gen ja_JP.UTF-8
  changed_when: true
  become: "{{ foundation_lxc_become_root }}"
