---
site_name: kanagawa01
site_short_name: kng01

ansible_user: ops
ansible_become: true

atlas_home: /opt/atlas
atlas_etc_dir: /etc/atlas
atlas_var_dir: /var/lib/atlas
atlas_tmp_dir: /opt/atlas/tmp
atlas_python_build_cache_path: /var/lib/atlas/cache/python-build

atlas_runtime_python_version: "3.12.3"

atlas_operator_user: "{{ ansible_user }}"
atlas_operator_group: "{{ atlas_operator_user }}"
atlas_operator_home: "{{ '/root' if atlas_operator_user == 'root' else '/home/' ~ atlas_operator_user }}"
atlas_operator_profile: "{{ atlas_operator_home }}/.profile"
atlas_pyenv_root: "{{ atlas_operator_home }}/.pyenv"
atlas_bootstrap_mode: managed
atlas_manage_host: "{{ atlas_bootstrap_mode != 'manual' }}"
atlas_become_root: "{{ ansible_user != 'root' }}"
atlas_become_operator: "{{ ansible_user != atlas_operator_user }}"

atlas_cli_venv: "{{ atlas_operator_home }}/.local/share/atlas-cli-venv"
atlas_cli_bin_dir: "{{ atlas_operator_home }}/.local/bin"
atlas_cli_bin: "{{ atlas_cli_bin_dir }}/atlas"
atlas_cli_source: "git+https://github.com/alflag-org/atlas.git@master"

atlas_releases:
  daedalus:
    source: daedalus

atlas_registries:
  daedalus:
    source: "git+https://github.com/alflag-org/daedalus.git#master"
