---
- name: Install Cloudflare SSH sshd drop-in
  ansible.builtin.copy:
    src: ./etc/ssh/sshd_config.d/00-cloudflare-ssh.conf
    dest: /etc/ssh/sshd_config.d/00-cloudflare-ssh.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart Cloudflare SSH sshd
  when: not foundation_cloudflare_ssh_skip_sshd | bool

- name: Install Cloudflare SSH CA
  ansible.builtin.copy:
    src: ./etc/ssh/ca.pub
    dest: /etc/ssh/ca.pub
    owner: root
    group: root
    mode: "0644"
  notify: Restart Cloudflare SSH sshd
  when: not foundation_cloudflare_ssh_skip_sshd | bool
