---
zabbix_primary_problem_source: true
zabbix_server_installation_managed: true
zabbix_intended_components:
  - zabbix-server
  - zabbix-frontend
  - zabbix-agent2
  - local-database

zabbix_dbhost: localhost
mysql_zabbix_dbname: zabbix
mysql_zabbix_user: zabbix
mysql_zabbix_monitor_user: zabbix_monitor
mysql_zabbix_auth_plugin: caching_sha2_password
mysql_zabbix_password_salt: daedalus_zabbix_user
mysql_zabbix_monitor_password_salt: daedalus_zbxmon_user

mysql_server_required_secret_vars:
  - mysql_zabbix_password
  - mysql_zabbix_monitor_password
mysql_server_bind_address: 127.0.0.1
mysql_server_databases:
  - name: "{{ mysql_zabbix_dbname }}"
    encoding: utf8mb4
    collation: utf8mb4_bin
mysql_server_users:
  - name: "{{ mysql_zabbix_user }}"
    host: localhost
    plugin: "{{ mysql_zabbix_auth_plugin }}"
    plugin_auth_string: "{{ mysql_zabbix_password }}"
    salt: "{{ mysql_zabbix_password_salt }}"
    priv: "{{ mysql_zabbix_dbname }}.*:ALL"
  - name: "{{ mysql_zabbix_monitor_user }}"
    host: 127.0.0.1
    plugin: "{{ mysql_zabbix_auth_plugin }}"
    plugin_auth_string: "{{ mysql_zabbix_monitor_password }}"
    salt: "{{ mysql_zabbix_monitor_password_salt }}"
    priv: "*.*:REPLICATION CLIENT,PROCESS,SHOW DATABASES,SHOW VIEW"
