---
common_operator_user: ops
common_operator_group: "{{ common_operator_user }}"
common_operator_home: "/home/{{ common_operator_user }}"
common_operator_shell: /bin/bash
common_operator_groups:
  - sudo
common_operator_authorized_key_files:
  - "{{ lookup('env', 'HOME') ~ '/.ssh/infra.pub' }}"
common_operator_sudoers_path: "/etc/sudoers.d/90-{{ common_operator_user }}"
common_operator_sudoers_content: "{{ common_operator_user }} ALL=(ALL) NOPASSWD:ALL"
common_operator_manage_authorized_keys: true
common_operator_manage_sudoers: true
common_operator_become_root: "{{ ansible_user != 'root' }}"
