---
- name: Create Atlas directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ atlas_operator_user }}"
    group: "{{ atlas_operator_group }}"
    mode: "0755"
  loop:
    - "{{ atlas_etc_dir }}"
    - "{{ atlas_home }}"
    - "{{ atlas_var_dir }}"
    - "{{ atlas_tmp_dir }}"
    - "{{ atlas_python_build_cache_path }}"
  become: true
