---
- name: Install pyenv
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ atlas_pyenv_root }}"
    version: master
    update: true
  become: "{{ atlas_become_operator }}"
  become_user: "{{ atlas_operator_user }}"

- name: Ensure pyenv shell profile
  ansible.builtin.blockinfile:
    path: "{{ atlas_operator_profile }}"
    marker: "# {mark} ANSIBLE MANAGED PYENV"
    create: true
    owner: "{{ atlas_operator_user }}"
    group: "{{ atlas_operator_group }}"
    mode: "0644"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      [[ -d "$PYENV_ROOT/bin" ]] && export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init - bash)"
  become: "{{ atlas_become_operator }}"
