---
all:
  children:
    default:
      children:
        mgmt:
          hosts: {}

        infra:
          hosts:
            game-control01:
              ansible_host: 10.10.20.63
            dns-recursive01:
              ansible_host: 10.10.20.240
            dns-recursive02:
              ansible_host: 10.10.20.241
            dns-authoritative01:
              ansible_host: 10.10.20.242
            dns-authoritative02:
              ansible_host: 10.10.20.243
            mysql-shared01:
              ansible_host: 10.10.20.221
            mysql-shared02:
              ansible_host: 10.10.20.222
            connector01:
              ansible_host: 10.10.20.41
            connector02:
              ansible_host: 10.10.20.42
            workbench01:
              ansible_host: 10.10.20.61
            control01:
              ansible_host: 10.10.20.62

        dmz:
          hosts:
            game-node01:
              ansible_host: 10.10.30.30

        provider_proxmox:
          hosts:
            game-control01: {}
            game-node01: {}
            dns-recursive01: {}
            dns-recursive02: {}
            dns-authoritative01: {}
            dns-authoritative02: {}
            mysql-shared01: {}
            mysql-shared02: {}
            connector01: {}
            connector02: {}
            workbench01: {}
            control01: {}

        platform_lxc:
          hosts:
            dns-recursive01: {}
            dns-recursive02: {}
            dns-authoritative01: {}
            dns-authoritative02: {}
            connector01: {}
            connector02: {}

        platform_vm:
          hosts:
            game-control01: {}
            game-node01: {}
            control01: {}
            mysql-shared01: {}
            mysql-shared02: {}
            workbench01: {}

        control_plane_nodes:
          hosts:
            control01: {}

        svc_dns_recursive:
          hosts:
            dns-recursive01: {}
            dns-recursive02: {}

        svc_dns_authoritative:
          hosts:
            dns-authoritative01: {}
            dns-authoritative02: {}

        svc_connector:
          hosts:
            connector01: {}
            connector02: {}

        svc_workbench:
          hosts:
            workbench01: {}

        svc_mysql:
          hosts:
            mysql-shared01: {}
            mysql-shared02: {}

        mysql_router_clients:
          hosts:
            workbench01: {}
            control01: {}

        svc_web:
          hosts: {}

        svc_netbox:
          hosts: {}

        svc_gameap_panel:
          hosts:
            game-control01: {}

        svc_gameap_daemon:
          hosts:
            game-node01: {}
