---
all:
  children:
    default:
      children:
        mgmt:
          hosts:
            dns-recursive01:
              ansible_host: 10.10.10.240
            dns-recursive02:
              ansible_host: 10.10.10.241
            dns-authoritative01:
              ansible_host: 10.10.10.242
            dns-authoritative02:
              ansible_host: 10.10.10.243
            monitor01:
              ansible_host: 10.10.10.250
            mysql-shared01:
              ansible_host: 10.10.10.221
            connector01:
              ansible_host: 10.10.10.41
            connector02:
              ansible_host: 10.10.10.42
            bastion01:
              ansible_host: 10.10.10.60
            workbench01:
              ansible_host: 10.10.10.61
            control01:
              ansible_host: 10.10.10.62

        dmz:
          hosts:
            web01:
              ansible_host: 10.10.30.21

        provider_proxmox:
          hosts:
            dns-recursive01: {}
            dns-recursive02: {}
            dns-authoritative01: {}
            dns-authoritative02: {}
            monitor01: {}
            mysql-shared01: {}
            connector01: {}
            connector02: {}
            bastion01: {}
            workbench01: {}
            control01: {}
            web01: {}

        platform_lxc:
          hosts:
            dns-recursive01: {}
            dns-recursive02: {}
            dns-authoritative01: {}
            dns-authoritative02: {}
            connector01: {}
            connector02: {}
            bastion01: {}

        platform_vm:
          hosts:
            control01: {}
            monitor01: {}
            mysql-shared01: {}
            workbench01: {}
            web01: {}

        cap_control_node:
          hosts:
            control01: {}

        svc_dns_recursive:
          hosts:
            dns-recursive01: {}
            dns-recursive02: {}

        svc_dns_authoritative:
          hosts:
            dns-authoritative01: {}
            dns-authoritative02: {}

        svc_connector:
          hosts:
            connector01: {}
            connector02: {}

        svc_bastion:
          hosts:
            bastion01: {}

        svc_workbench:
          hosts:
            workbench01: {}

        svc_monitoring:
          hosts:
            monitor01: {}

        svc_mysql:
          hosts:
            mysql-shared01: {}

        svc_web:
          hosts:
            web01: {}
