---
- name: Converge foundation components
  ansible.builtin.import_playbook: components/foundation.yml

- name: Converge Web host middleware
  ansible.builtin.import_playbook: components/nginx.yml

- name: Converge service components
  ansible.builtin.import_playbook: components/services.yml
