---
- name: Converge foundation components
  ansible.builtin.import_playbook: components/foundation.yml

- name: Converge control-plane components
  ansible.builtin.import_playbook: components/control-plane.yml

- name: Converge service components
  ansible.builtin.import_playbook: components/services.yml
