---
- name: Set fact swap_file_path and swap_file_size_mb
  ansible.builtin.set_fact:
    swap_file_path: "{{ swap_file_path | default('/swapfile') }}"  # noqa var-naming[no-role-prefix]
    swap_file_size_mb: "{{ swap_file_size_mb | default(8192) | int }}"  # noqa var-naming[no-role-prefix]

- name: Check active swap files
  ansible.builtin.command: swapon --show=NAME --noheadings --raw
  register: swap_file_active_files  # noqa var-naming[no-role-prefix]
  changed_when: false
  check_mode: false

- name: Check if swap file exists
  ansible.builtin.stat:
    path: "{{ swap_file_path }}"
  register: swap_file  # noqa var-naming[no-role-prefix]

- name: Set fact swap_file_is_active
  ansible.builtin.set_fact:
    swap_file_is_active: "{{ swap_file_path in (swap_file_active_files.stdout_lines | default([])) }}"  # noqa var-naming[no-role-prefix]

- name: Set fact swap_file_existing_size_mb if swap file exists
  ansible.builtin.set_fact:
    swap_file_existing_size_mb: "{{ (swap_file.stat.size / 1024 / 1024) | int }}"  # noqa var-naming[no-role-prefix]
  when: swap_file.stat.exists

- name: Set fact swap_file_existing_size_mb to 0 if not swap file exists
  ansible.builtin.set_fact:
    swap_file_existing_size_mb: 0  # noqa var-naming[no-role-prefix]
  when: not swap_file.stat.exists
