---
- name: Disable swap file
  ansible.builtin.command: swapoff "{{ swap_file_path }}"
  become: true
  changed_when: true
  when: swap_file_is_active | bool

- name: Remove swap file
  ansible.builtin.file:
    path: "{{ swap_file_path }}"
    state: absent
  become: true
