---
- name: Read current timezone
  ansible.builtin.command:
    cmd: timedatectl show --property=Timezone --value
  changed_when: false
  register: common_vm_timezone

- name: Set timezone
  ansible.builtin.command:
    cmd: timedatectl set-timezone Asia/Tokyo
  changed_when: true
  when: common_vm_timezone.stdout != 'Asia/Tokyo'
  become: true
