---
hostname: topmost01-mgmt-mysql-shared-01
site: topmost01
zone: mgmt
role: mysql
purpose: shared
virtualization_type: vm
os_distribution: Ubuntu
os_version: "26.04"

network_address: 10.10.10.221/24
network_ipv4_address: 10.10.10.221
network_prefix_length: 24
network_gateway: 10.10.10.1
network_dns_resolvers:
  - 10.10.10.240
  - 10.10.10.241
network_primary_fqdn: topmost01-mgmt-mysql-shared-01.srv.alflag.internal
network_service_aliases:
  - mysql-shared.srv.alflag.internal

systemd_resolved_dns:
  - 10.10.10.240
  - 10.10.10.241
systemd_resolved_domains:
  - srv.alflag.internal

ssh_server_enabled: true
systemd_resolved_enabled: true
zabbix_agent_enabled: true
